
version: "3.9"
services:
  app:
    container_name: 'nodejs-container'
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '/usr/app/node_modules'
      - '.:/usr/app'
      - '/tmp:/tmp' # volume logs
    ports:
      - '3000:3000'
    command: yarn pm2:start
    environment:
      - NODE_ENV=production
      - PORT=3000
      - URI_CHANNEL=amqp://guest:guest@rabbitmq
    networks:
      - app-network
    links:
      - rabbitmq

  rabbitmq:
    container_name: 'rabbitmq-container'
    image: rabbitmq:3.8-management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - '5673:5672'
      - '15673:15672'
    volumes:
      - '~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/'
      - '~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq'
    networks:
      - app-network

networks:
  app-network:
    driver: bridge