
version: "3.9"
services:
  app:
    container_name: 'nodejs-container'
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '/usr/app/node_modules'
      - '.:/usr/app'
    ports:
      - '3000:3000'
    command: yarn pm2:start
    environment:
      - NODE_ENV=production
      - PORT=3000
      - URI_CHANNEL=amqp://rabbitmq
    networks:
      - app-network
    links:
      - rabbitmq

  rabbitmq:
    container_name: 'rabbitmq-container'
    image: rabbitmq:3.8-management-alpine
    networks:
      - app-network

networks:
  app-network:
    driver: bridge